services:
    php:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-dev
        restart: unless-stopped
        tty: true
        # ports:
        #   - "9000:9000"
        volumes:
            - .:/var/www
            - ./.platform/files/laravel.ini:/usr/local/etc/php/conf.d/docker-php-custom.ini
        #command: "supervisord -c /etc/supervisor/supervisord.conf"
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.default.conf:/etc/nginx/conf.d/default.conf
            - .data/nginx/logs:/var/log/nginx
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
