name: larasense.com

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install PHP Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Install NPM dependencies and compile assets
        run: |
          npm ci
          npm run build --if-present

      - name: Execute tests
        run: composer test

      - name: Commit compiled assets
        uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ github.event_name == 'push' }}
        with:
          commit_message: Compile assets

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.1.0
        if: ${{ github.event_name == 'push' }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd scripts && sh larasense.com.sh
